Repository ardatan/graphql-mesh, pull requests merged in 2020-08, with the labels that each got.

#784 fix(openapi): handle integers better for enums and 64-bit values
  packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
  packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
  packages/handlers/openapi/test/__snapshots__/handler.spec.ts.snap
  packages/handlers/openapi/test/example_api.test.ts
Labels: bug

#807 fix(transforms): apply transforms for input object type fields
  .changeset/quiet-ladybugs-count.md
  packages/transforms/filter-schema/src/index.ts
  packages/transforms/rename/src/index.ts
Labels: bug

#806 chore(deps): bump graphql-tools
  .changeset/brown-dots-taste.md
  package.json
  packages/cli/package.json
  packages/handlers/graphql/package.json
  packages/mergers/federation/package.json
  packages/mergers/stitching/package.json
  packages/runtime/package.json
  packages/transforms/cache/package.json
  packages/transforms/filter-schema/package.json
  packages/transforms/mock/package.json
  packages/transforms/naming-convention/package.json
  packages/transforms/prefix/package.json
  packages/transforms/rename/package.json
  packages/transforms/resolvers-composition/package.json
  packages/transforms/snapshot/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: dependencies

#815 Remove heavy depenedencies from OpenAPI handler
  .changeset/quick-yaks-begin.md
  .changeset/strong-islands-eat.md
  examples/openapi-stackexchange/.meshrc.yml
  packages/handlers/openapi/package.json
  packages/handlers/openapi/src/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/auth_builder.ts
  packages/handlers/openapi/src/openapi-to-graphql/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
  packages/handlers/openapi/src/openapi-to-graphql/preprocessor.ts
  packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
  packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
  packages/handlers/openapi/src/openapi-to-graphql/types/options.ts
  packages/handlers/openapi/src/openapi-to-graphql/utils.ts
  packages/handlers/openapi/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  schema.graphql
  yarn.lock
Labels: enhancement

#814 fix(runtime): handle non query operations in proxy sdk
  .changeset/slow-pumas-smile.md
  packages/runtime/src/resolvers-hooks.ts
Labels: bug

#813 fix(openapi): handle missing baseUrl properly
  .changeset/clean-radios-roll.md
  packages/handlers/openapi/src/index.ts
Labels: bug

#818 feat(cache): introduce new caching strategy localforage
  .changeset/tasty-feet-protect.md
  packages/cache/localforage/package.json
  packages/cache/localforage/src/index.ts
  packages/cache/localforage/test/cache.spec.ts
  packages/cache/localforage/yaml-config.graphql
  packages/runtime/src/get-mesh.ts
  packages/runtime/src/parse-config.ts
  packages/runtime/src/types.ts
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  schema.graphql
  yarn.lock
Labels: feature

#821 fix(openapi): do not pass falsy values to query string and headers
  .changeset/tall-seahorses-beam.md
  packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
Labels: bug

#823 fix(openapi): handle falsy arguments properly
  .changeset/fast-peas-whisper.md
  .changeset/tall-seahorses-beam.md
  packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
  packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
Labels: bug

#826 fix(cache): handle default cache as inmemory-lru
  .changeset/shaggy-gifts-roll.md
  packages/cache/inmemory-lru/yaml-config.graphql
  packages/runtime/src/utils.ts
  schema.graphql
Labels: bug

#828 fix(handlers): grpc empty proto
  .changeset/tiny-cherries-happen.md
  packages/handlers/grpc/src/utils.ts
  packages/handlers/grpc/test/handler.spec.ts
  packages/handlers/grpc/test/utils.spec.ts
Labels: bug

#836 feat(postgraphile): more options
  .changeset/tame-comics-hunt.md
  .github/workflows/check-configuration.yml
  package.json
  packages/handlers/openapi/package.json
  packages/handlers/openapi/src/openapi-to-graphql/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/types/options.ts
  packages/handlers/openapi/test/authentication.test.ts
  packages/handlers/openapi/test/cloudfunction.test.ts
  packages/handlers/openapi/test/docusign.test.ts
  packages/handlers/openapi/test/example_api.test.ts
  packages/handlers/openapi/test/example_api2.test.ts
  packages/handlers/openapi/test/example_api3.test.ts
  packages/handlers/openapi/test/example_api4.test.ts
  packages/handlers/openapi/test/example_api5.test.ts
  packages/handlers/openapi/test/example_api6.test.ts
  packages/handlers/openapi/test/government_social_work.test.ts
  packages/handlers/openapi/test/ibm_language_translator.test.ts
  packages/handlers/openapi/test/instagram.test.ts
  packages/handlers/openapi/test/stripe.test.ts
  packages/handlers/openapi/test/weather_underground.test.ts
  packages/handlers/postgraphile/src/index.ts
  packages/handlers/postgraphile/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  schema.graphql
  scripts/introspect-config.js
  tsconfig.build.json
  yarn.lock
Labels: feature

#839 Export generateSdk function
  .changeset/swift-cherries-hunt.md
  packages/cli/src/index.ts
Labels: feature

#842 fix(runtime): handle empty transforms array
  .changeset/blue-toes-relate.md
  packages/cache/localforage/src/index.ts
  packages/runtime/src/get-mesh.ts
  packages/types/src/index.ts
Labels: bug

#844 Update cache.md docs
  website/docs/transforms/cache.md
Labels: documentation

#845 Update cache.md invalidates to invalidate
  website/docs/transforms/cache.md
Labels: documentation

#855 Update cache.md with correct match key for operation based cache invalidation example
  website/docs/transforms/cache.md
Labels: documentation

#869 feat(config): able to configure serve command in mesh config file
  .changeset/few-dots-warn.md
  examples/federation-example/.meshrc.yml
  examples/federation-example/package.json
  examples/grpc-example/.meshrc.yml
  examples/grpc-example/package.json
  examples/hasura-openbrewery-geodb/.meshrc.yml
  examples/hasura-openbrewery-geodb/package.json
  examples/json-schema-covid/.meshrc.yml
  examples/json-schema-covid/package.json
  examples/json-schema-example/.meshrc.yml
  examples/json-schema-example/package.json
  examples/mongoose-example/package.json
  examples/mysql-employees/package.json
  examples/mysql-rfam/.meshrc.yml
  examples/mysql-rfam/package.json
  examples/neo4j-example/package.json
  examples/odata-trippin/.meshrc.yml
  examples/odata-trippin/package.json
  examples/openapi-javascript-wiki/.meshrc.yaml
  examples/openapi-javascript-wiki/package.json
  examples/openapi-location-weather/package.json
  examples/openapi-stackexchange/.meshrc.yml
  examples/openapi-stackexchange/package.json
  examples/openapi-stripe/.meshrc.yml
  examples/openapi-stripe/package.json
  examples/openapi-youtrack/.meshrc.yml
  examples/openapi-youtrack/package.json
  examples/postgres-geodb/package.json
  examples/soap-country-info/.meshrc.yml
  examples/soap-country-info/package.json
  examples/sqlite-chinook/.meshrc.yml
  examples/sqlite-chinook/package.json
  examples/thrift-calculator/package.json
  packages/cli/package.json
  packages/cli/src/bin.ts
  packages/cli/src/commands/serve/serve.ts
  packages/cli/src/commands/serve/yaml-config.graphql
  packages/config/src/index.ts
  packages/config/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  website/docs/recipes/as-gateway.md
  yarn.lock
Labels: feature

#871 fix(odata): add $count to odata query options
  .changeset/silent-ears-compare.md
  packages/handlers/odata/src/index.ts
  packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
Labels: enhancement
