Repository ardatan/graphql-mesh, pull requests merged in 2020-12, with the labels that each got.

#1191 feat(config): support code files in additionalTypeDefs
  .changeset/real-lemons-swim.md
  packages/config/package.json
  packages/config/src/utils.ts
  packages/handlers/neo4j/src/index.ts
Labels: feature

#1193 feat: allow to filter by type
  .changeset/dirty-geese-chew.md
  packages/transforms/filter-schema/src/index.ts
  packages/transforms/filter-schema/test/transform.spec.ts
Labels: feature

#1314 enhance(openapi): improve sanitizing and prevent conflict between sanitized names
  .changeset/chatty-moles-fetch.md
  .changeset/quick-rabbits-speak.md
  packages/handlers/openapi/src/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
  packages/handlers/openapi/src/openapi-to-graphql/preprocessor.ts
  packages/handlers/openapi/test/authentication.test.ts
  packages/handlers/openapi/test/example_api.test.ts
  packages/handlers/openapi/test/example_api4.test.ts
  packages/transforms/encapsulate/src/index.ts
  packages/transforms/encapsulate/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
Labels: enhancement

#1330 fix(utils): handle multiple transforms properly
  .changeset/lovely-wolves-compare.md
  packages/transforms/encapsulate/test/encapsulate.spec.ts
  packages/utils/src/apply-transforms.ts
Labels: bug
