Repository ardatan/graphql-mesh, pull requests merged in 2020-10, with the labels that each got.

#1007 fix(docs): Remove leading $ to fix copy
  website/docs/getting-started/basic-example.md
  website/docs/getting-started/installation.md
Labels: documentation

#1011 fix(runtime): prefer same operation type during stitching
  .changeset/eighty-shoes-bow.md
  .changeset/kind-fishes-grow.md
  .changeset/shy-wombats-compare.md
  packages/cli/src/index.ts
  packages/mergers/stitching/src/mergeSingleSchema.ts
  packages/runtime/src/resolvers-hooks.ts
Labels: bug

#1010 feat(openapi): add sourceFormat option to provide schema format explicitly
  .changeset/nice-frogs-vanish.md
  packages/handlers/openapi/src/index.ts
  packages/handlers/openapi/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  packages/utils/src/read-file-or-url.ts
Labels: feature

#1009 enhance(caching): improve introspection caching
  .changeset/gold-fishes-brush.md
  packages/handlers/graphql/package.json
  packages/handlers/graphql/src/index.ts
  packages/handlers/graphql/yaml-config.graphql
  packages/handlers/postgraphile/src/index.ts
  packages/handlers/postgraphile/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  yarn.lock
Labels: enhancement

#1020 feat(serve) support cookies and static file serving
  .changeset/early-geckos-obey.md
  examples/odata-microsoft/.meshrc.yml
  examples/odata-microsoft/example-queries/fetchFilesFromOneDrive.graphql
  examples/odata-microsoft/example-queries/fetchGroupsAndMembers.graphql
  examples/odata-microsoft/example-queries/fetchRecentEmails.graphql
  examples/odata-microsoft/package.json
  examples/odata-microsoft/public/index.html
  examples/odata-microsoft/src/index.ts
  packages/cli/package.json
  packages/cli/src/commands/serve/playground.ts
  packages/cli/src/commands/serve/serve.ts
  packages/cli/src/commands/serve/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  yarn.lock
Labels: feature

#1024 feat(neo4j): add typeDefs option to provide custom schema
  .changeset/thirty-cars-tan.md
  examples/neo4j-example/.gitignore
  examples/neo4j-example/.meshrc.yml
  examples/neo4j-example/package.json
  packages/handlers/neo4j/package.json
  packages/handlers/neo4j/src/index.ts
  packages/handlers/neo4j/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  yarn.lock
Labels: feature

#1025 feat(odata): add Duration scalar for Edm.Duration type
  .changeset/seven-pets-relax.md
  .changeset/twenty-schools-report.md
  packages/cli/src/commands/scalars-map.ts
  packages/handlers/grpc/package.json
  packages/handlers/json-schema/package.json
  packages/handlers/mysql/package.json
  packages/handlers/odata/package.json
  packages/handlers/odata/src/index.ts
  packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
  packages/handlers/openapi/package.json
  packages/handlers/thrift/package.json
  yarn.lock
Labels: automerge, feature

#1035 fix(runtime): map schemas to rawSources correctly
  .changeset/purple-socks-wink.md
  packages/runtime/src/resolvers-hooks.ts
Labels: bug

#1048 feat(openapi): handle callbacks as subscriptions
  .changeset/wild-pets-double.md
  examples/json-schema-subscriptions/.meshrc.yml
  examples/json-schema-subscriptions/CHANGELOG.md
  examples/json-schema-subscriptions/addTodo.json
  examples/json-schema-subscriptions/api.js
  examples/json-schema-subscriptions/package.json
  examples/json-schema-subscriptions/todo.json
  examples/json-schema-subscriptions/todos.json
  examples/openapi-subscriptions/.meshrc.yml
  examples/openapi-subscriptions/api.js
  examples/openapi-subscriptions/example-queries/listenWebhook.mutation.graphql
  examples/openapi-subscriptions/example-queries/startWebhook.subscription.graphql
  examples/openapi-subscriptions/openapi.yml
  examples/openapi-subscriptions/package.json
  packages/handlers/openapi/src/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/preprocessor.ts
  packages/handlers/openapi/src/openapi-to-graphql/resolver_builder.ts
  packages/handlers/openapi/src/openapi-to-graphql/types/options.ts
  packages/handlers/openapi/src/openapi-to-graphql/utils.ts
  website/docs/recipes/subscriptions-webhooks.md
  yarn.lock
Labels: feature
