Repository ardatan/graphql-mesh, pull requests merged in 2020-11, with the labels that each got.

#1135 fix(cli): generate typescript definitions properly
  .changeset/unlucky-boxes-repeat.md
  packages/cli/src/commands/typescript.ts
  yarn.lock
Labels: bug

#1151 feat(json-schema): support baseSchema
  .changeset/green-seas-confess.md
  examples/json-schema-fhir/.meshrc.yml
  examples/json-schema-fhir/example.query.graphql
  examples/json-schema-fhir/fhir.schema.json
  examples/json-schema-fhir/package.json
  examples/json-schema-fhir/sandbox.config.json
  packages/handlers/json-schema/src/index.ts
  packages/handlers/json-schema/src/json-schema-visitor.ts
  packages/handlers/json-schema/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
  yarn.lock
Labels: automerge, feature

#1158 feat(mysql): add an ability to use existing Pool instance
  .changeset/silent-wasps-roll.md
  packages/handlers/mysql/package.json
  packages/handlers/mysql/src/index.ts
  packages/handlers/mysql/yaml-config.graphql
  packages/types/src/config-schema.json
  packages/types/src/config.ts
Labels: feature

#1134 fix(redis-cache): stringify before saving values
  .changeset/clever-files-arrive.md
  packages/cache/redis/src/index.ts
Labels: bug

#1164 Fix/mysql handler pool usage
  .changeset/light-days-cry.md
  .gitignore
  packages/handlers/mysql/src/index.ts
Labels: bug

#1179 fix(federation-transform): do not search for unavailable type and throw correct message
  .changeset/fair-insects-destroy.md
  packages/transforms/federation/src/index.ts
Labels: bug

#1185 Add defaults to gRPC LoadOptions
  .changeset/eight-taxis-mate.md
  packages/handlers/grpc/yaml-config.graphql
Labels: enhancement
