Repository ardatan/graphql-mesh, pull requests merged in 2020-06, with the labels that each got.

#575 Fix root level transforms
  packages/mergers/federation/src/index.ts
  packages/mergers/stitching/package.json
  packages/mergers/stitching/src/index.ts
Labels: bug

#578 Improve the tests of naming convention transform for input types
  packages/transforms/cache/test/cache.spec.ts
  packages/transforms/naming-convention/test/naming-convention.spec.ts
Labels: automerge, bug

#584 Ignore GraphQLResolveInfo if `fields` option is defined in in-context sdk
  packages/handlers/grpc/src/index.ts
  packages/handlers/mysql/src/index.ts
  packages/handlers/odata/src/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/index.ts
  packages/handlers/openapi/src/openapi-to-graphql/oas_3_tools.ts
  packages/handlers/openapi/src/openapi-to-graphql/preprocessor.ts
  packages/handlers/openapi/src/openapi-to-graphql/schema_builder.ts
  packages/handlers/openapi/src/openapi-to-graphql/utils.ts
  packages/runtime/src/get-mesh.ts
  packages/runtime/src/parse-config.ts
  packages/runtime/src/resolvers-hooks.ts
  packages/runtime/src/types.ts
  packages/types/src/index.ts
Labels: bug

#587 Update graphql-tools monorepo
  package.json
  packages/cli/package.json
  packages/handlers/graphql/package.json
  packages/mergers/federation/package.json
  packages/mergers/stitching/package.json
  packages/runtime/package.json
  packages/transforms/cache/package.json
  packages/transforms/filter-schema/package.json
  packages/transforms/mock/package.json
  packages/transforms/naming-convention/package.json
  packages/transforms/prefix/package.json
  packages/transforms/rename/package.json
  packages/transforms/resolvers-composition/package.json
  packages/transforms/snapshot/package.json
  packages/types/package.json
  packages/utils/package.json
  yarn.lock
Labels: automerge, dependencies

#603 fix(postgraphile-getMeshSource): Fallback to empty array when no plugins
  packages/handlers/postgraphile/src/index.ts
Labels: bug

#597 Add original context object as target in proxyContext
  packages/cli/src/commands/typescript.ts
  packages/runtime/src/get-mesh.ts
  packages/runtime/src/resolvers-hooks.ts
  packages/runtime/src/types.ts
Labels: bug

#605 Use `Byte`, `Date`, `Time`, `UtcOffset` and `Timestamp` from graphql-scalars
  packages/cli/src/commands/scalars-map.ts
  packages/handlers/grpc/package.json
  packages/handlers/json-schema/package.json
  packages/handlers/mysql/package.json
  packages/handlers/mysql/src/index.ts
  packages/handlers/odata/package.json
  packages/handlers/odata/src/index.ts
  packages/handlers/odata/test/__snapshots__/handler.spec.ts.snap
  packages/handlers/openapi/package.json
  packages/handlers/thrift/package.json
  packages/handlers/thrift/src/index.ts
  yarn.lock
Labels: enhancement

#616 fix(federation): Named operations
  .github/workflows/tests.yml
  .gitignore
  packages/cli/src/commands/typescript.ts
  packages/mergers/federation/src/index.ts
  packages/types/src/config.ts
Labels: bug

#627 fix(json-schema-handler): add missing scalars
  packages/handlers/json-schema/src/index.ts
  packages/handlers/json-schema/src/json-schema-types.ts
  packages/handlers/json-schema/src/json-schema-visitor.ts
  website/package.json
  yarn.lock
Labels: bug
